name: Serverless Deploy - Contact Form

on:
  workflow_dispatch:
  push:
    branches:
      - feature/contact

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: serverless
      - name: Install Required NPM Dependencies
        working-directory: serverless
        run: npm ci
      - name: Serverless Deploy
        uses: serverless/github-action@master
        with:
          args: deploy --config serverless/serverless.yml --stage adam-test
